-- ============================================================
-- 🗳️ FaceVote — Supabase PostgreSQL Database Schema
-- Run this script in your Supabase SQL Editor:
-- https://supabase.com/dashboard/project/bzqtnkwtpyregccfwseo/sql
-- ============================================================

-- Enable pgvector extension for biometric vector embeddings
CREATE EXTENSION IF NOT EXISTS vector;

-- ------------------------------------------------------------
-- 1. VOTERS TABLE
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.voters (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    voter_id TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    face_embedding JSONB NOT NULL, -- 512-dimensional vector stored as JSON array or vector
    eligibility_status TEXT NOT NULL DEFAULT 'ELIGIBLE',
    has_voted INTEGER NOT NULL DEFAULT 0,
    voted_at TIMESTAMPTZ,
    voted_session_id TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_voters_voter_id ON public.voters(voter_id);
CREATE INDEX IF NOT EXISTS idx_voters_eligibility ON public.voters(eligibility_status);

-- ------------------------------------------------------------
-- 1B. MULTI-TEMPLATE FACE EMBEDDINGS TABLE
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.face_embeddings (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    voter_uuid UUID NOT NULL REFERENCES public.voters(id) ON DELETE CASCADE,
    voter_id TEXT NOT NULL,
    face_embedding JSONB NOT NULL,
    quality_score FLOAT NOT NULL DEFAULT 1.0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_face_embeddings_voter_uuid ON public.face_embeddings(voter_uuid);
CREATE INDEX IF NOT EXISTS idx_face_embeddings_voter_id ON public.face_embeddings(voter_id);

-- ------------------------------------------------------------
-- 2. VOTING SESSIONS TABLE
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.voting_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT UNIQUE NOT NULL,
    share_token TEXT UNIQUE NOT NULL,
    title TEXT NOT NULL,
    description TEXT,
    start_time TIMESTAMPTZ NOT NULL,
    end_time TIMESTAMPTZ NOT NULL,
    ended_at TIMESTAMPTZ,
    status TEXT NOT NULL DEFAULT 'SCHEDULED',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by TEXT DEFAULT 'admin'
);

CREATE INDEX IF NOT EXISTS idx_voting_sessions_session_id ON public.voting_sessions(session_id);
CREATE INDEX IF NOT EXISTS idx_voting_sessions_share_token ON public.voting_sessions(share_token);

-- ------------------------------------------------------------
-- 3. CANDIDATES TABLE
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.candidates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES public.voting_sessions(session_id) ON DELETE CASCADE,
    candidate_id TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    party_or_position TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_candidates_session_id ON public.candidates(session_id);

-- ------------------------------------------------------------
-- 4. VOTES TABLE (STRICT UNIQUE CONSTRAINT FOR ONE VOTE PER SESSION)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.votes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id TEXT NOT NULL REFERENCES public.voting_sessions(session_id) ON DELETE CASCADE,
    voter_id TEXT NOT NULL REFERENCES public.voters(voter_id) ON DELETE CASCADE,
    candidate_id TEXT NOT NULL REFERENCES public.candidates(candidate_id) ON DELETE CASCADE,
    cast_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT unique_voter_per_session UNIQUE(session_id, voter_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_unique_session_voter ON public.votes(session_id, voter_id);
CREATE INDEX IF NOT EXISTS idx_votes_candidate ON public.votes(candidate_id);

-- ------------------------------------------------------------
-- 5. ROW LEVEL SECURITY (RLS) POLICIES
-- ------------------------------------------------------------
ALTER TABLE public.voters ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.face_embeddings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.voting_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.candidates ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.votes ENABLE ROW LEVEL SECURITY;

-- Allow anonymous read/write operations for API client access
CREATE POLICY "Allow public select voters" ON public.voters FOR SELECT USING (true);
CREATE POLICY "Allow public insert voters" ON public.voters FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update voters" ON public.voters FOR UPDATE USING (true);
CREATE POLICY "Allow public delete voters" ON public.voters FOR DELETE USING (true);

CREATE POLICY "Allow public select face_embeddings" ON public.face_embeddings FOR SELECT USING (true);
CREATE POLICY "Allow public insert face_embeddings" ON public.face_embeddings FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public delete face_embeddings" ON public.face_embeddings FOR DELETE USING (true);

CREATE POLICY "Allow public select sessions" ON public.voting_sessions FOR SELECT USING (true);
CREATE POLICY "Allow public insert sessions" ON public.voting_sessions FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update sessions" ON public.voting_sessions FOR UPDATE USING (true);

CREATE POLICY "Allow public select candidates" ON public.candidates FOR SELECT USING (true);
CREATE POLICY "Allow public insert candidates" ON public.candidates FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow public select votes" ON public.votes FOR SELECT USING (true);
CREATE POLICY "Allow public insert votes" ON public.votes FOR INSERT WITH CHECK (true);
